### ISSUE TITLE
Questions about test phase~

### ISSUE THREAD

**Issue by wujiekd** [joanrod/ocr-vqgan#1]
Hello, during the test, we will input GT, and then generate images to compare with GT?

**Comment by joanrod** [comment]
That's correct. You evaluate the model at a reconstruction task.

**Comment by canghao** [comment]
Hello, have you tried any subsequent text and image generation work based on the OCR-VQGAN model? Is it through the Transformer autoregressive model in the paper? How is the effect? Do you have any suggestions?
