### ISSUE TITLE
Questions about the pre-training model

### ISSUE THREAD

**Issue by wujiekd** [joanrod/ocr-vqgan#2]
Hello, which CRAFT model do you use? Is there a corresponding link? Thank you and look forward to your reply.

**Comment by joanrod** [comment]
Hello, and thanks for reaching out,

we use the ```craft_mlt_25k.pth``` checkpoint which can be downloaded through the CRAFT GitHub repository https://github.com/clovaai/CRAFT-pytorch.

In their models' table, they call this model "General", and it can be downloaded directly [here](https://drive.google.com/file/d/1Jk4eGD7crsqCCg9C9VjCLkMN3ze8kutZ/view)

**Comment by wujiekd** [comment]
> Hello, and thanks for reaching out,
> 
> we use the `craft_mlt_25k.pth` checkpoint which can be downloaded through the CRAFT GitHub repository https://github.com/clovaai/CRAFT-pytorch.
> 
> In their models' table, they call this model "General", and it can be downloaded directly [here](https://drive.google.com/file/d/1Jk4eGD7crsqCCg9C9VjCLkMN3ze8kutZ/view)

Thank you for your reply!
