### ISSUE TITLE
about text to image

### ISSUE THREAD

**Issue by canghao** [joanrod/ocr-vqgan#7]
Hello, have you tried any subsequent text to image generation work based on the OCR-VQGAN model? Is it through the Transformer autoregressive model in the paper? How is the effect? Do you have any suggestions?

**Comment by joanrod** [comment]
Hello @canghao, we have a follow-up work on text-to-image using OCR-VQGAN and Latent Diffusion models, results are promising! (https://arxiv.org/abs/2306.00800). Autoregressive Transformer is a real option (i.e. DALLE-like), I would suggest trying with the new trends in transformers, and compare against our diffusion-based model

**Comment by canghao** [comment]
Thank you very much for your reply. The code provided in the FIGGEN paper cannot be obtained due to other reasons. Could you please provide the code and relevant information for this job again (such as pre training weight files)? Another approach is to combine OCR-VQGAN and CLIP models for text and image alignment. Currently, some people have tried this approach. Do you think this method can be tried on datasets like Paper2Fig100k?

**Comment by zjysteven** [comment]
I was also wondering if the repo for FigGen is still available. Meanwhile, how does FigGen handle the actual data for the plots (by "actual data" I mean, e.g., the height of bars in a bar plot), or it is purely based on the text caption?

**Comment by zjysteven** [comment]
> Thank you very much for your reply. The code provided in the FIGGEN paper cannot be obtained due to other reasons. Could you please provide the code and relevant information for this job again (such as pre training weight files)? Another approach is to combine OCR-VQGAN and CLIP models for text and image alignment. Currently, some people have tried this approach. Do you think this method can be tried on datasets like Paper2Fig100k?

@canghao I'm totally new to this field but am interested. Do you mind pointing me to some of the papers that you mentioned having tried to "combine OCR-VQGAN and CLIP"?

**Comment by canghao** [comment]
@zjysteven I'm currently new to the field of text to image. I am learning the VQGAN-CLIP model by reading relevant papers and code. (https://arxiv.org/abs/2204.08583 and https://github.com/nerdyrodent/VQGAN-CLIP). I hope it can be helpful to you!

**Comment by joanrod** [comment]
@zjysteven @canghao I'm glad you are interested, there are a number of things that can be done. VQGAN+CLIP is an interesting direction, one could finetune CLIP (using https://github.com/mlfoundations/open_clip) with Paper2Fig100k and that would give us a lot more options. We can sit and chat about it if you want.

The code for FigGen will be available soon :)

UPDATE: FigGen is public at github.com/joanrod/figure-diffusion/
