### ISSUE TITLE
`paper2fig_train.json` and `paper2fig_test.json` not included in `Paper2Fig100k.tar.gz`

### ISSUE THREAD

**Issue by potamides** [joanrod/ocr-vqgan#9]
Hi, thanks for your cool work!

I have tried to download the [Paper2Fig100k dataset](https://zenodo.org/records/7299423#.Y_dxrezMJqu), but the provided `tar.gz` file does not seem to include the `json` files with metadata as advertised. Where can I find these files?

**Comment by joanrod** [comment]
Hi, thanks for your interest! 

The json files are indeed available in the tar.gz. I downloaded it again and find the files there (see screenshot). Could you check again?

![image](https://github.com/joanrod/ocr-vqgan/assets/97542291/54199611-dc32-4f08-9fc3-f60db3752a55)

**Comment by potamides** [comment]
Thank you for your swift response. I just checked again, and indeed the files are there. I wonder why I did not find them yesterday. Perhaps, since I am navigating the tar archive without extracting it, I overlooked them since they are stored at the very end of the archive. In either case, sorry for the noise!

**Comment by joanrod** [comment]
No problem! Feel free to contact me if I can help with anything
